import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-800 antialiased">
        <div className="max-w-3xl mx-auto px-4 py-10">
          <header className="mb-12">
            <h1 className="text-3xl font-bold tracking-tight">
              LearnedOps
      </h1>
            <p className="text-gray-500 mt-2">
              DevOps — Beyond Tools. Finance — Beyond Money.
      </p>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
